sudo: false
notifications:
  email: false
language: python
install:
- wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
- bash miniconda.sh -b -p $HOME/miniconda
- export PATH="$HOME/miniconda/bin:$PATH"
- hash -r
- conda config --set always_yes yes --set changeps1 no
- conda update -q conda
- conda info -a
- conda install -c conda-forge python=3.7
- python setup.py install
script:
- python test.py
deploy:
  provider: pypi
  user: "__token__"
  password:
    secure: z/BOL2oVtjxdAiRB1YqsWPCeMUgjq5DRpxqfYzRkKF2rXo8ZBH38sxSLiWmadNOpMcow9FV5qQ+V5e0dlp0zoF6zI1d7e0Rb6Lk+lv3P9GyrPeEJtRwdfiXcgy1OfpSbjyANn7DN0tyHyP73JA+DIl2LcZCi4JgorEGFlNptYp+YKZ/u4Q6tRp8kPjcDk+VoLJ8R01/nXRGOS8A4XuA5k3DmoedeJJPEDad53jrJ5Gu//T4pUTP9dg47UajRZJKhrzp7qRk8hSHqtwVtCYUobyOcZIeocunXyLDTB5PNXp0qJhuaqhemUzbA1zDy7r5H0RRh2B+kbObYhJ3hY7qIdjwJ89+WeZMSrb+j153oiLR2dKp3deRDRDiKvBqd3/JsB3zv49r+CihM03P0tGAINloPnoGasT/UTCV0Vi9WuwKKEbCQlmImdjzbujTNkj3UuULgRNcrIiHc/m5vaC1lJ0TdLRFY8cXPdWfbXDZD0vR85YMQT8cXmt3NBkx4r6p8YPlqDx8Xj7z0EHgfEb4P3s8omMtIFfilIX4N9YbopRh8EqbAi6vX9fzqS6LMgTmoGR8qe/w0Qne8RQCGsKNbcla0AcGiwoNf2TUi6NdETODeblJUkBTAB9SKQGx4F+cGE2dztgWMjeEjVlvARXAFKZDp5tNGoxY8sfxcXO8U9MU=
  distributions: sdist bdist_wheel
  on:
    branch: master
    tags: true
