# meta.yaml
{% set version = '0.0.37' %}

package:
  version: {{ version }}
  name: 'daytum-intake-data'

source:
  git_rev: v{{ version }}
  git_url: https://github.com/daytum/daytum-intake-data

build:
  number: 0
  noarch: generic

requirements:
  run:
    - intake >=0.5.4
    - intake-sql >=0.2.0
    - intake-parquet >=0.2.3
    - psycopg2 >=2.8.4
  build: []

about:
  description: Production history and well meta data from US oil and gas wells
  license: Apache v2.0
  license_family: Apache
  summary: Production history and well meta data from US oil and gas wells
