# meta.yaml
package:
  version: '0.0.2'
  name: 'data'

source:
  git_rev: v0.0.2
  git_url: https://github.com/daytum/intake-data

build:
  number: 0
  noarch: generic

requirements:
  run:
    - intake
  build: []

about:
  description: Production history from US oil and gas wells
  license: Apache v2.0
  license_family: MIT
  summary: Production history from US oil and gas wells
