# meta.yaml
package:
  version: '0.0.4'
  name: 'data'

source:
  git_rev: v0.0.4
  git_url: https://github.com/daytum/intake-data

build:
  number: 0
  noarch: generic

requirements:
  run:
    - psycopg2
    - intake
    - intake-sql
    - intake-parquet
  build: []

about:
  description: Production history from US oil and gas wells
  license: Apache v2.0
  license_family: Apache
  summary: Production history from US oil and gas wells
